### ISSUE TITLE
go mod compatibility

### ISSUE THREAD

**Issue by sodul** [kubernetes-sigs/aws-iam-authenticator#264]
As `go dep` is officially deprecated we are trying to remove it entirely from our toolchain. As such we have upgraded from `retool` to `gobin` with great success and `aws-iam-authenticator` is our last tool that we use that still fails to build with `go module`.

Steps to reproduce:
* install gobin: `GO111MODULE=off go get -u github.com/myitcv/gobin`
* install `aws-iam-authenticator` with gobin:
```
$ gobin github.com/kubernetes-sigs/aws-iam-authenticator/cmd/aws-iam-authenticator@v0.4.0
failed to run go get -d github.com/kubernetes-sigs/aws-iam-authenticator/cmd/aws-iam-authenticator@v0.4.0: exit status 1
go: finding github.com/kubernetes-sigs/aws-iam-authenticator/cmd/aws-iam-authenticator v0.4.0
go: finding github.com/kubernetes-sigs/aws-iam-authenticator/cmd v0.4.0
go: finding github.com/prometheus/client_golang/prometheus/promhttp latest
go: finding github.com/prometheus/client_golang/prometheus latest
go: finding github.com/aws/aws-sdk-go/aws/credentials latest
go: finding github.com/aws/aws-sdk-go/service/ec2 latest
go: finding github.com/aws/aws-sdk-go/aws/session latest
go: finding github.com/aws/aws-sdk-go/aws latest
go: finding github.com/aws/aws-sdk-go/service/sts latest
go: finding github.com/aws/aws-sdk-go/aws/credentials/stscreds latest
go: finding k8s.io/api/authentication/v1beta1 latest
go: finding k8s.io/api/authentication latest
go: finding k8s.io/api latest
go: finding github.com/aws/aws-sdk-go/aws/endpoints latest
go: finding k8s.io/client-go/pkg/apis/clientauthentication/v1alpha1 latest
go: finding k8s.io/apimachinery/pkg/apis/meta latest
go: finding k8s.io/apimachinery/pkg/apis latest
go: finding k8s.io/apimachinery/pkg latest
go: finding github.com/aws/aws-sdk-go/aws/ec2metadata latest
go: finding k8s.io/apimachinery latest
go: finding github.com/aws/aws-sdk-go/aws/arn latest
go: finding github.com/aws/aws-sdk-go/service latest
go: finding github.com/aws/aws-sdk-go v1.23.19
go: downloading github.com/aws/aws-sdk-go v1.23.19
go: finding k8s.io/client-go/pkg/apis/clientauthentication latest
go: finding k8s.io/client-go/pkg/apis latest
go: finding k8s.io/client-go/pkg latest
go: extracting github.com/aws/aws-sdk-go v1.23.19
go: github.com/christopherhein/go-version@v0.1.0: parsing go.mod: unexpected module path "go.hein.dev/go-version"
go: finding github.com/russross/blackfriday v1.5.2
go: error loading module requirements
```

OS: Ubuntu 18.04 and macOS 10.14.6
CPU: amd64

https://github.com/myitcv/gobin

The root issue is in the `go.mod` file of `go-version` so we also filed an issue there: https://github.com/christopherhein/go-version/issues/16

**Comment by nckturner** [comment]
This should be fixed @sodul, can you confirm and reopen if not?

**Comment by sodul** [comment]
Hi Nicholas,

Thank you for working on this but unfortunately there are still issues:

```gobin github.com/kubernetes-sigs/aws-iam-authenticator/cmd/aws-iam-authenticator@master
failed to run go get -d github.com/kubernetes-sigs/aws-iam-authenticator/cmd/aws-iam-authenticator@master: exit status 1
go: finding github.com/kubernetes-sigs/aws-iam-authenticator/cmd/aws-iam-authenticator master
go: finding github.com/kubernetes-sigs/aws-iam-authenticator/cmd master
go: finding github.com/kubernetes-sigs/aws-iam-authenticator master
go: github.com/kubernetes-sigs/aws-iam-authenticator@v0.4.1-0.20191026222816-f3b285caacda: parsing go.mod: unexpected module path "sigs.k8s.io/aws-iam-authenticator"
go: error loading module requirements
```

**Comment by rifelpet** [comment]
You need to import it as `sigs.k8s.io/aws-iam-authenticator/cmd/aws-iam-authenticator` rather than `github.com/kubernetes-sigs/aws-iam-authenticator/cmd/aws-iam-authenticator`

**Comment by sodul** [comment]
Using `sigs.k8s.io` worked:
```
$ gobin sigs.k8s.io/aws-iam-authenticator/cmd/aws-iam-authenticator@master
Installed sigs.k8s.io/aws-iam-authenticator/cmd/aws-iam-authenticator@v0.4.1-0.20191026222816-f3b285caacda to /Users/stephane/go/bin/aws-iam-authenticator
```

Thank you!

**Comment by sodul** [comment]
Unfortunately the issue is back:
```
$ gobin sigs.k8s.io/aws-iam-authenticator/cmd/aws-iam-authenticator@v0.4.1-0.20191026222816-f3b285caacda
failed to run go get -d sigs.k8s.io/aws-iam-authenticator/cmd/aws-iam-authenticator@v0.4.1-0.20191026222816-f3b285caacda: exit status 1
go: finding sigs.k8s.io/aws-iam-authenticator/cmd/aws-iam-authenticator v0.4.1-0.20191026222816-f3b285caacda
go: finding sigs.k8s.io/aws-iam-authenticator/cmd v0.4.1-0.20191026222816-f3b285caacda
go: finding sigs.k8s.io/aws-iam-authenticator v0.4.1-0.20191026222816-f3b285caacda
go: downloading sigs.k8s.io/aws-iam-authenticator v0.4.1-0.20191026222816-f3b285caacda
go: extracting sigs.k8s.io/aws-iam-authenticator v0.4.1-0.20191026222816-f3b285caacda
go: finding github.com/aws/aws-sdk-go v1.23.11
go: finding github.com/gofrs/flock v0.7.0
go: finding golang.org/x/tools v0.0.0-20190814235402-ea4142463bf3
go: finding k8s.io/client-go v0.0.0-20190425172711-65184652c889
go: finding k8s.io/api v0.0.0-20190425012535-181e1f9c52c1
go: finding k8s.io/apimachinery v0.0.0-20190612125636-6a5db36e93ad
go: finding k8s.io/apiextensions-apiserver v0.0.0-20190426053235-842c4571cde0
go: finding k8s.io/code-generator v0.0.0-20190419212335-ff26e7842f9d
go: finding k8s.io/component-base v0.0.0-20190612130303-4062e14deebe
go: finding github.com/gophercloud/gophercloud v0.0.0-20190126172459-c818fa66e4c8
go: finding k8s.io/sample-controller v0.0.0-20190425173525-f9c23632fb31
go: finding go.hein.dev/go-version v0.1.0
go: go.hein.dev/go-version@v0.1.0: unknown revision go-version/v0.1.0
go: finding github.com/gogo/protobuf v0.0.0-20171007142547-342cbe0a0415
go: finding golang.org/x/oauth2 v0.0.0-20190402181905-9f3314589c9a
go: finding github.com/google/gofuzz v0.0.0-20170612174753-24818f796faf
go: finding golang.org/x/crypto v0.0.0-20181025213731-e84da0312774
go: finding github.com/gregjones/httpcache v0.0.0-20170728041850-787624de3eb7
go: finding github.com/imdario/mergo v0.3.5
go: finding k8s.io/klog v0.3.0
go: finding github.com/peterbourgon/diskv v2.0.1+incompatible
go: finding golang.org/x/time v0.0.0-20161028155119-f51c12702a4d
go: finding k8s.io/apimachinery v0.0.0-20190425132440-17f84483f500
go: finding golang.org/x/net v0.0.0-20190206173232-65e2d4e15006
go: finding github.com/evanphx/json-patch v0.0.0-20190203023257-5858425f7550
go: finding github.com/google/btree v0.0.0-20160524151835-7d79101e329e
go: finding github.com/dgrijalva/jwt-go v0.0.0-20160705203006-01aeca54ebda
go: finding k8s.io/utils v0.0.0-20190221042446-c2654d5206da
go: finding github.com/Azure/go-autorest v11.1.2+incompatible
go: error loading module requirements
```

Targeting master is not working better:
```
obin sigs.k8s.io/aws-iam-authenticator/cmd/aws-iam-authenticator@master
failed to run go get -d sigs.k8s.io/aws-iam-authenticator/cmd/aws-iam-authenticator@master: exit status 1
go: finding sigs.k8s.io/aws-iam-authenticator/cmd/aws-iam-authenticator master
go: finding sigs.k8s.io/aws-iam-authenticator/cmd master
go: finding sigs.k8s.io/aws-iam-authenticator master
go: downloading sigs.k8s.io/aws-iam-authenticator v0.4.1-0.20191125220208-e02e263de571
go: extracting sigs.k8s.io/aws-iam-authenticator v0.4.1-0.20191125220208-e02e263de571
go: finding go.hein.dev/go-version v0.1.0
go: go.hein.dev/go-version@v0.1.0: unknown revision go-version/v0.1.0
go: error loading module requirements
```
